version: '3.9'

services:
  server:
    container_name: server
    image: server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    env_file:
      - .env
    environment:
      - MONGODB_CONNECTION=mongodb://mongo:27017/main
    depends_on:
      - mongo
      
  mongo:
    container_name: mongo
    image: mongo:4.4.29
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=main
    volumes:
      - mongodbdata:/var/lib/mongo/data
    
volumes:
  mongodbdata:
    driver: local